### ISSUE TITLE
Too many requests (again)

### ISSUE THREAD

**Issue by jollijumper** [conradreisch/CoinGeckoPortfolio-MoneyMoney#5]
It happend again since thursday 16th :-(

<img width="450" alt="Bildschirmfoto 2023-12-19 um 22 06 21" src="https://github.com/dark-m0de/CoinGeckoPortfolio-MoneyMoney/assets/1527883/bfe3718c-26ef-4a8d-914b-154723489157">

<img width="643" alt="Bildschirmfoto 2023-12-19 um 22 06 39" src="https://github.com/dark-m0de/CoinGeckoPortfolio-MoneyMoney/assets/1527883/61693fb5-1c77-49ed-bbf1-1713191d5187">

_Originally posted by @jollijumper in https://github.com/dark-m0de/CoinGeckoPortfolio-MoneyMoney/issues/4#issuecomment-1863475117_

**Comment by jollijumper** [comment]
This time after the 6th asset and 45 sec.  it run into the error.

<img width="170" alt="Bildschirmfoto 2023-12-21 um 22 36 31" src="https://github.com/dark-m0de/CoinGeckoPortfolio-MoneyMoney/assets/1527883/02102130-0147-4278-a659-1080f60bbd23">

**Comment by dark-m0de** [comment]
Hi @jollijumper, 
thanks for bringing this up. It looks like the new rate limit now hits after six requests.
I will change the plugin and add a feature so that you can pass a parameter with a delay in milliseconds. Whatever the rate limit will be in the future, you can then adjust the delay yourself. 
Because it is christmas season, it might take a few days until I can do this and get it signed by MM.
Enjoy the holidays. I will keep you posted.
Best regards

**Comment by jollijumper** [comment]
Thank you for your feedback and support. 
Take your time and enjoy the christmas holidays.

Merry christmas 🎄

**Comment by dark-m0de** [comment]
I just created an update (see [branch v1.2](https://github.com/dark-m0de/CoinGeckoPortfolio-MoneyMoney/tree/v1.2)) and sent it to MoneyMoney for signing.

The update implements the following logic:
- Up to five coins, the api get queried with zero delay.
- For more than 5 coins, a delay of 12s is automatically applied.
- In case the limits change again, there is the option to manually override the delay (in ms), followed by a semicolon. 
Example: `DELAY(12000);POLKADOT(10),CARDANO(100)`

As soon as I have the signed version, I will merge the branch and create a new release. Without signature, you can only use the code in a beta version of MoneyMoney with deactivated signature verification.

**Comment by jollijumper** [comment]
Thats a nice present 🎁 
Merry Christmas 🎄 Enjoy your holidays.

**Comment by dark-m0de** [comment]
You're welcome. Merry Christmas 🎄
